{
 "title": "PROOOD dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Текущий день системы",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT day FROM settings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество рекламных объявлений",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(campaign_id) FROM campaigns LIMIT 50 "
    }
   ]
  },
  {
   "title": "Общий доход сервиса",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cost) FROM events GROUP BY day ORDER BY day ASC "
    }
   ]
  },
  {
   "title": "Распределение пользователей по полу",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(gender) FROM clients GROUP BY gender LIMIT 50 "
    }
   ]
  },
  {
   "title": "Распределение действий",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(CASE WHEN type = 'view' THEN 1 ELSE 0 END) AS \"Просмотры\",\n    SUM(CASE WHEN type = 'click' THEN 1 ELSE 0 END) AS \"Клики\"\nFROM events;\n"
    }
   ]
  },
  {
   "title": "Статистика по дням",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(CASE WHEN type = 'view' THEN 1 ELSE 0 END) AS \"Просмотры\",\n    SUM(CASE WHEN type = 'click' THEN 1 ELSE 0 END) AS \"Клики\",\n    day,\n    SUM(cost) AS \"Заработок\"\nFROM events\nGROUP BY day\nORDER BY day ASC;\n"
    }
   ]
  },
  {
   "title": "Количество пользователей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(client_id) FROM clients LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество рекламодателей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(campaign_id) FROM campaigns LIMIT 50 "
    }
   ]
  },
  {
   "title": "Самые прибыльные рекламы",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    c.ad_title AS \"Название кампании\",\n    SUM(e.cost) AS \"Заработок\"\nFROM events e\nJOIN campaigns c ON e.campaign_id = c.campaign_id\nGROUP BY c.ad_title\nORDER BY \"Заработок\" DESC;\n"
    }
   ]
  }
 ]
}